name: Services

on:
  push:
    branches: [main]
    paths:
      - services/**
      - "!services/web/**"
      - .github/workflows/api.yml
  pull_request:
    paths:
      - services/**
      - "!services/web/**"
      - .github/workflows/api.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: services

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.8"
          cache-dependency-path: services/go.work.sum

      - run: go vet ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.8"
          cache-dependency-path: services/go.work.sum

      - run: go test ./... -v -race -short
